import fs from "node:fs";
import { fileURLToPath } from "node:url";

const escapeHtml = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const voidTags = new Set(["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"]);

/** Translate this project's controlled HTML template using tag boundaries, including nested footer markup. */
export function renderLocalePage(template, messages, locale) {
  const text = (key) => {
    if (typeof messages[key] !== "string") throw new Error(`Missing ${locale} translation: ${key}`);
    return escapeHtml(messages[key]);
  };
  const replacements = [];
  const stack = [];
  for (const match of template.matchAll(/<!--[\s\S]*?-->|<\/?[a-zA-Z][^>]*>/g)) {
    const tag = match[0];
    if (tag.startsWith("<!--")) continue;
    const name = tag.match(/^<\/?([\w-]+)/)[1].toLowerCase();
    if (tag.startsWith("</")) {
      const node = stack.pop();
      if (!node || node.name !== name) throw new Error(`Unbalanced template: ${name}`);
      if (node.key) replacements.push({ start: node.contentStart, end: match.index, value: text(node.key) });
      continue;
    }
    let translated = tag;
    for (const attribute of ["aria-label", "title", "placeholder", "alt", "href"]) {
      const key = tag.match(new RegExp(`\\bdata-i18n-${attribute}="([^"]+)"`))?.[1];
      if (!key) continue;
      const pattern = new RegExp(`(?<![\\w-])${attribute}="[^"]*"`);
      translated = pattern.test(translated)
        ? translated.replace(pattern, `${attribute}="${text(key)}"`)
        : translated.replace(/>$/, ` ${attribute}="${text(key)}">`);
    }
    if (translated !== tag) replacements.push({ start: match.index, end: match.index + tag.length, value: translated });
    if (!voidTags.has(name) && !tag.endsWith("/>")) {
      stack.push({ name, contentStart: match.index + tag.length, key: tag.match(/\bdata-i18n="([^"]+)"/)?.[1] });
    }
  }
  if (stack.length) throw new Error("Unclosed template tag");
  // A translated parent, like footer.name, has textContent semantics and replaces its descendants.
  const edits = replacements.filter((edit) => !replacements.some((other) => other !== edit
    && other.start <= edit.start && other.end >= edit.end));
  let html = template;
  for (const edit of edits.sort((a, b) => b.start - a.start)) html = html.slice(0, edit.start) + edit.value + html.slice(edit.end);
  const origin = "https://varzia.starport1116.com";
  html = html.replace(/<html[^>]*>/, `<html lang="${locale === "zh" ? "zh-CN" : "en"}" data-route-locale="${locale}">`)
    .replace(/<title>[\s\S]*?<\/title>/, `<title>${text("seo.title")}</title>`)
    .replace(/(<link rel="canonical" href=")[^"]+/, `$1${origin}/${locale}/`);
  html = html.replace(/(<a class="brand" href=")[^"]+/, `$1/${locale}/`)
    .replace(/(id="sharedPlanReturn" href=")[^"]+/, `$1/${locale}/#planner`);
  const metadata = {
    description: messages["seo.description"], "og:title": messages["seo.title"],
    "og:description": messages["seo.ogDescription"], "og:locale": locale === "zh" ? "zh_CN" : "en_US",
    "og:url": `${origin}/${locale}/`, "twitter:title": messages["seo.title"],
    "twitter:description": messages["seo.description"]
  };
  for (const [key, value] of Object.entries(metadata)) {
    html = html.replace(new RegExp(`(<meta (?:name|property)="${key}" content=")[^"]*`), `$1${escapeHtml(value)}`);
  }
  const embedded = JSON.stringify(messages).replaceAll("<", "\\u003c").replaceAll(">", "\\u003e").replaceAll("&", "\\u0026");
  html = html.replace('    <script type="module" src="/js/app.js"></script>',
    `    <script type="application/json" id="localeMessages">${embedded}</script>\n    <script type="module" src="/js/app.js"></script>`);
  return html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by npm run build:locales. Edit index.html and data/locales instead. -->");
}

export function buildLocalePages({ check = false } = {}) {
  const root = new URL("../", import.meta.url);
  const template = fs.readFileSync(new URL("index.html", root), "utf8");
  for (const [locale, filename] of [["en", "en"], ["zh", "zh-cn"]]) {
    const messages = JSON.parse(fs.readFileSync(new URL(`data/locales/${filename}.json`, root)));
    const page = renderLocalePage(template, messages, locale);
    const output = new URL(`${locale}/index.html`, root);
    if (check) {
      if (fs.readFileSync(output, "utf8") !== page) throw new Error(`${locale}/index.html is out of date. Run npm run build:locales.`);
    } else fs.writeFileSync(output, page);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) buildLocalePages({ check: process.argv.includes("--check") });
